# Matrices - 2D Numpy

* Tables / Matrices
* Creating dummy
* Creating Matrices (Three ways to do it)
    * np.array()
    * np.reshape() C like behaviour (C like population of matrix)
    * np.reshape() F like behaviour (Fortran like population of matrix)
* Matrices Attributes
    * dimension
    * shape
    * size
* Indexation-Accessing different elements of a Numpy Array
* Matrix Operations 
    * Matrix Division
    * +, -, transpose 
    * Matrix round()
* Quiz on 2D Numpy Array 
* Object Oriented Concept

### What is Matrices - 2D Array 

* Alot of data is stored in form of tables and matrix is one of the ways to work with tables in Python 
* Further, we will be working with data frames and matrices are a great stepping stone towards data frames 
* Matrix is representation of a table of data 

OBS! In python a matrix is populated row by row by default (Unlike in R, where the colums are populated first)

In [ ]:
# Tables/Matrices (have a second dimension)
# Matrix is two dimensional array 

In [11]:
# Creating data to play with 
import numpy as np
mydata = np.arange(0,20) #it gives us some data to play with; starts with 0 and 20 not included 
print(mydata) #[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Creating Matrices 

In [1]:
# Creating Matrices - Method 01
# by using function np.array (lists are passed in this function)
# it works by putting rows into Matrix so it combines data elements into Matrix i.e., lists combined into matrix row by row

import numpy as np

r1 = ["I", "am", "happy"]
r2 = ["What", "a", "day"]
r3 = [1,2,3]

[r1, r2, r3] # [['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

np.array([r1, r2, r3])
#array([['I', 'am', 'happy'],
#       ['What', 'a', 'day'],
#       ['1', '2', '3']], dtype='<U5')  # Each number 1, 2, 3 is converted into string 
                                        # as in arrays you have only one type of elements
                                        # Extra information: what type the array has; U= Unicode; 5 Characters 
                                        # Less than 5 Uni code characters 
print(np.array([r1, r2, r3])) #if dont want to see extra info 

matrix = np.array([r1, r2, r3])
matrix # to view a matrix

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]


array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions, referred to as the rank.


In [4]:
# Show the numpy array dimensions

matrix.ndim

2

Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.


In [5]:
# Show the numpy array shape

matrix.shape

(3, 3)

The total number of elements in the array is given by the attribute <code>size</code>.


In [6]:
# Show the numpy array size

matrix.size

9

In [17]:
# Creating Matrices - Method 02
# using function np.reshape(*,*,'C')
# takes a list of data and it reshaped it into certain dimensions that you specify 
# imput 1: Data that you are reshaping 
# imput 2: Dimension; passed on as touple 
# input 3: defines how datais populated in matrix.. 
#          C : C-like population of Matrix. The programming language C (which has influenced python)
#          (data got populated in the matrix row by row)

np.reshape(mydata, (5,4)) # In python a matrix is populated row by row by default (Unlike in R, where the colums are populated first)
MATR1 = np.reshape(mydata, (5,4), order='C') 

In [20]:
# Creating Matrices - Method 03
# using function np.reshape(*,*,'F')
# takes a list of data and it reshaped it into certain dimensions that you specify 
# imput 1: Data that you are reshaping 
# imput 2: Dimension 
# input 3: defines how data is populated in matrix.. 
#          F : F-like population of Matrix.  (data got populated in the matrix column by column - top to bottom
MATR2 = np.reshape(mydata, (5,4), order='F') 

<h2 id="access">Indexation-Accessing different elements of a Numpy Array</h2>


We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500" />


We can access the 2nd-row, 3rd column as shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400" />


We simply use the square brackets and the indices corresponding to the element we would like:


In [7]:
# Access the element on the second row and third column

A[1, 2]

23

We can also use the following notation to obtain the elements:


In [8]:
# Access the element on the second row and third column

A[1][2]

23

Consider the elements shown in the following figure


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400" />


We can access the element as follows:


In [9]:
# Access the element on the first row and first column

A[0][0]

11

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400" />


This can be done with the following syntax:


In [10]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Similarly, we can obtain the first two rows of the 3rd column as follows:


In [11]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

Corresponding to the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="550"><br />


In [42]:
# Indexation - practice 

one = [80,77,82,82,73,82,58,78,6,35]
two = [82,57,82,79,76,72,60,72,79,80]
three = [79,78,75,81,76,79,62,76,77,69]
four = [80,65,77,66,69,77,55,67,77,40]
five = [82,82,82,79,82,78,54,76,71,41]

matr3 = np.array([one, two, three, four, five])

#print(matr3) 
# [[80 77 82 82 73 82 58 78  6 35]
# [82 57 82 79 76 72 60 72 79 80]
# [79 78 75 81 76 79 62 76 77 69]
# [80 65 77 66 69 77 55 67 77 40]
#  [82 82 82 79 82 78 54 76 71 41]]


#matr3[0] is same as matr[0,:]
#matr3[2,9] is same as matr[2][9], matr[2][-1], matr[2,-1]
#print(matr3[0])  # array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35])
#print(matr3[0,:]) #[80 77 82 82 73 82 58 78  6 35]


print(matr3[0,:]) # [80 77 82 82 73 82 58 78  6 35]
print(matr3[:,9]) # [35 80 69 40 41]
print(matr3[1:5, 1:8]) 
# [[57 82 79 76 72 60 72]
# [78 75 81 76 79 62 76]
# [65 77 66 69 77 55 67]
# [82 82 79 82 78 54 76]]


[80 77 82 82 73 82 58 78  6 35]
[35 80 69 40 41]
[[57 82 79 76 72 60 72]
 [78 75 81 76 79 62 76]
 [65 77 66 69 77 55 67]
 [82 82 79 82 78 54 76]]
[80 77 82 82 73 82 58 78  6 35]


---

<h2 id="op">Basic Operations</h2>


We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500" />


The numpy array is given by <code>X</code> and <code>Y</code>


In [12]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

We can add the numpy arrays as follows.


In [14]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500" />


We can perform the same operation in numpy as follows


In [15]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500" />


We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:


In [17]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:


First, we define matrix <code>A</code> and <code>B</code>:


In [20]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function <code>dot</code> to multiply the arrays together.


In [22]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [23]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the numpy attribute <code>T</code> to calculate the transposed matrix


In [24]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [25]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
# Matrix Operations - Matrix Division 

# Matrix Division is interesting to us because we can use it to normalize the values and find more insights into our data. 

# Motivation: 
#    In case of Matrix division, in case of large matrix, diving each value by associated element of other matrix can 
#    involve nested loops. matrix opterions gives a quicker solution without involving loops. 

# Matrix Division 
# Two matrices should have the same size or dimension
# Matries are divided element by asscoiated element of other matrix

In [ ]:
# Matrix Operations - Matrix round 
#   used to round off the values 
#   In matrix, we cannot use the normal round function. We will get error if we use that 
#   There is a special matrix round function in numpy package. (designed for matrics)

np.matrix.round()

In [ ]:
# Benifits of Normalization 
# Normalization process allows us to come with more comparable values 

<h2>Quiz on 2D Numpy Array</h2>


Consider the following list <code>a</code>, convert it to Numpy Array.


In [27]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<details><summary>Click here for the solution</summary>

```python
A = np.array(a)
A
```

</details>


Calculate the numpy array size.


In [28]:
# Write your code below and press Shift+Enter to execute
A.size

12

<details><summary>Click here for the solution</summary>

```python
A.size
```

</details>


Access the element on the first row and first and second columns.


In [31]:
# Write your code below and press Shift+Enter to execute
A[0, 0:2]

array([1, 2])

<details><summary>Click here for the solution</summary>

```python
A[0][0:2]
```

</details>


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [34]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

X = np.dot(A, B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

<details><summary>Click here for the solution</summary>

```python
X = np.dot(A,B)
X
```

</details>


### Object Oriented Programming Concept 

In [24]:
# Object Oriented Programming Concept 
# One way of finding this function (reshape) is to go to the package where its definitely stored because thats where it 
# come from and then apply that function to the object or data
# use object oriented approach
# as mydata is an array type(mydata) # numpy.ndarray (as we can created it useing np.arrange() function)
# So, mydata is actually an object (which already contains reshape function, 
# so we can apply the function (reshape)  within object 
# and dont have to go to the package and find function at the package 
# We can write np.reshape(mydata,(5,4)) as 
mydata.reshape(5,4)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])